### ISSUE TITLE
编译报错：TypeError: Cannot destructure property 'node' of 'res[0]' as it is null.

### ISSUE THREAD

**Issue by EPSON-LEE** [daniel-zd/taro-f2-react#3]
@antv/f2: "^4.0.39",
Taro v3.5.10

**Comment by wanglihuaya** [comment]
俺也一样

**Comment by daniel-zd** [comment]
@EPSON-LEE @wanglihuaya 
Hello，感谢问题反馈，经过测试 Taro 3.5.1 以下版本可用，发现是 Taro 升级后造成自定义组件中的 Canvas 组件没有成功挂载所致，建议可将问题提给 Taro

**Comment by wanglihuaya** [comment]
![image](https://user-images.githubusercontent.com/49522285/215960937-bde0e92e-7fe7-4497-aabd-b77459f05bd9.png)
目前 创建canvas，没有res[0]

**Comment by daniel-zd** [comment]
@wanglihuaya 原因是在 dev 开发模式下，taro-f2-react 中的 Canvas 未被成功挂载，在通过 createSelectorQuery 查找 f2Canvas 时未找到该组件，所以 res 实际返回为 null
刚才测试在 build 模式下也是正常的，只有在 dev 模式下有问题，

**Comment by daniel-zd** [comment]
@wanglihuaya 建议先回退 Taro 版本

**Comment by wanglihuaya** [comment]
> @wanglihuaya 原因是在 dev 开发模式下，taro-f2-react 中的 Canvas 未被成功挂载，在通过 createSelectorQuery 查找 f2Canvas 时未找到该组件，所以 res 实际返回为 null 刚才测试在 build 模式下也是正常的，只有在 dev 模式下有问题，

行 我试试build模式下，要不试试把代码中的res[0]都改为res？

**Comment by wanglihuaya** [comment]
> @wanglihuaya 建议先回退 Taro 版本

目前也不是强依赖，项目中目前使用的是echarts，会有一些内存泄漏问题，导致小程序闪退，想试试 antv 好像也有问题

下面是一个代码片段
https://developers.weixin.qq.com/s/bGfkAGmc7BFL

手机预览下，应该都会崩掉

点击按钮 来回切换页面 进进出出
但是 开发者工具检测 Memory 内存又没 溢出

**Comment by daniel-zd** [comment]
Taro 在 >= 3.6.0 版本中已经解决了 Dev 模式下 npm 包组件挂载的问题

**Comment by lhzbxx** [comment]
> Taro 在 >= 3.6.0 版本中已经解决了 Dev 模式下引用 npm 包中组件挂载不上的问题

是某项配置的问题么？我在 Taro 3.6.2 中使用默认配置，Dev 模式下依旧存在该问题。

**Comment by daniel-zd** [comment]
@lhzbxx 
按照以下配置修改，看起来还是 Taro 新版本中 Dev 编译模式下是有 bug 的，先这样
````javascript
{
  ...
  compiler: {
    type: 'webpack5',
    prebundle: {
      enable: false,
    },
  },
  ...
}
`
